---
- name: install jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: importing rpm key for jenkins
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present

- name: install jenkins 
  yum:
    name: jenkins
    state: present

- name: start jenkins service
  systemd:
    name: jenkins
    state: started
